<?php


 /**
  * Artesano Data Access Object (DAO).
  * This class contains all database handling that is needed to 
  * permanently store and retrieve Artesano object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



class ArtesanoDao 
{


    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    function createValueObject() {
          return new Artesano();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    function getObject($conn, $idArtesano) {

          $valueObject = $this->createValueObject();
          $valueObject->setIdArtesano($idArtesano);
          $this->load($conn, $valueObject);
          return $valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    function load($conn, $valueObject) {

          if (!$valueObject->getIdArtesano()) {
               //print "Can not select without Primary-Key!";
               return false;
          }

          $sql = "SELECT * FROM artesano WHERE (idArtesano = ".$valueObject->getIdArtesano().") "; 

          if ($this->singleQuery($conn, $sql, $valueObject))
               return true;
          else
               return false;
    }
    /**
     * LoadAll-method. This will read all contents from database table and
     * build an Vector containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    function loadAll($conn) {


          $sql = "SELECT * FROM artesano ORDER BY idArtesano ASC ";

          $searchResults = $this->listQuery($conn, $sql);

          return $searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    function create($conn, $valueObject) {

          $sql = "INSERT INTO artesano (TipoDoc, NroDoc, ";
          $sql = $sql."password, direccion, telefono, telefono2, ";
          $sql = $sql."username, estado, nombre, ";
          $sql = $sql."celular, email, certificacion, ";
          $sql = $sql."nivelestudio, aprendices, cursos, ";
          $sql = $sql."formatofoto,departamento,ciudad) VALUES (";
          $sql = $sql."".$valueObject->getTipoDoc().", ";
          $sql = $sql."'".$valueObject->getNroDoc()."', ";
          $sql = $sql."'".$valueObject->getPassword()."', ";
          $sql = $sql."'".$valueObject->getDireccion()."', ";
          $sql = $sql."'".$valueObject->getTelefono()."', ";
          $sql = $sql."'".$valueObject->getTelefono2()."', ";
          $sql = $sql."'".$valueObject->getUsername()."', ";
          $sql = $sql."".$valueObject->getEstado().", ";
          $sql = $sql."'".$valueObject->getNombre()."', ";
          $sql = $sql."'".$valueObject->getCelular()."', ";
          $sql = $sql."'".$valueObject->getEmail()."', ";
          $sql = $sql."".$valueObject->getCertificacion().", ";
          $sql = $sql."".$valueObject->getNivelestudio().", ";
          $sql = $sql."'".$valueObject->getAprendices()."', ";
          $sql = $sql."'".$valueObject->getCursos()."', ";
          $sql = $sql."'".$valueObject->getFormatofoto()."', ";
          $sql = $sql."'".$valueObject->getDepartamento()."', ";
          $sql = $sql."'".$valueObject->getCiudad()."') ";
          $result = $this->databaseUpdate($conn, $sql);


          return true;
    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    function save($conn, $valueObject) {

          $sql = "UPDATE artesano SET TipoDoc = ".$valueObject->getTipoDoc().", ";
          $sql = $sql."NroDoc = '".$valueObject->getNroDoc()."', ";
          $sql = $sql."password = '".$valueObject->getPassword()."', ";
          $sql = $sql."direccion = '".$valueObject->getDireccion()."', ";
          $sql = $sql."telefono = '".$valueObject->getTelefono()."', ";
          $sql = $sql."telefono2 = '".$valueObject->getTelefono2()."', ";
          $sql = $sql."username = '".$valueObject->getUsername()."', ";
          $sql = $sql."estado = ".$valueObject->getEstado().", ";
          $sql = $sql."nombre = '".$valueObject->getNombre()."', ";
          $sql = $sql."celular = '".$valueObject->getCelular()."', ";
          $sql = $sql."email = '".$valueObject->getEmail()."', ";
          $sql = $sql."certificacion = ".$valueObject->getCertificacion().", ";
          $sql = $sql."nivelestudio = ".$valueObject->getNivelestudio().", ";
          $sql = $sql."aprendices = '".$valueObject->getAprendices()."', ";
          $sql = $sql."cursos = '".$valueObject->getCursos()."', ";
          $sql = $sql."formatofoto = '".$valueObject->getFormatofoto()."'";
          $sql = $sql."departamento = '".$valueObject->getDepartamento()."'";
          $sql = $sql."ciudad = '".$valueObject->getCiudad()."'";
          $sql = $sql." WHERE (idArtesano = ".$valueObject->getIdArtesano().") ";
          $result = $this->databaseUpdate($conn, $sql);

          if ($result != 1) {
               //print "PrimaryKey Error when updating DB!";
               return false;
          }

          return true;
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    function delete($conn, $valueObject) {


          if (!$valueObject->getIdArtesano()) {
               //print "Can not delete without Primary-Key!";
               return false;
          }

          $sql = "DELETE FROM artesano WHERE (idArtesano = ".$valueObject->getIdArtesano().") ";
          $result = $this->databaseUpdate($conn, $sql);

          if ($result != 1) {
               //print "PrimaryKey Error when updating DB!";
               return false;
          }
          return true;
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    function deleteAll($conn) {

          $sql = "DELETE FROM artesano";
          $result = $this->databaseUpdate($conn, $sql);

          return true;
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    function countAll($conn) {

          $sql = "SELECT count(*) FROM artesano";
          $allRows = 0;

          $result = $conn->execute($sql);

          if ($row = $conn->nextRow($result))
                $allRows = $row[0];

          return $allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in vector, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    function searchMatching($conn, $valueObject) {

          $first = true;
          $sql = "SELECT * FROM artesano WHERE 1=1 ";

          if ($valueObject->getIdArtesano() != 0) {
              if ($first) { $first = false; }
              $sql = $sql."AND idArtesano = ".$valueObject->getIdArtesano()." ";
          }

          if ($valueObject->getTipoDoc() != 0) {
              if ($first) { $first = false; }
              $sql = $sql."AND TipoDoc = ".$valueObject->getTipoDoc()." ";
          }

          if ($valueObject->getNroDoc() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND NroDoc = '".$valueObject->getNroDoc()."' ";
          }

          if ($valueObject->getPassword() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND password LIKE '".$valueObject->getPassword()."%' ";
          }

          if ($valueObject->getDireccion() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND direccion LIKE '".$valueObject->getDireccion()."%' ";
          }

          if ($valueObject->getTelefono() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND telefono LIKE '".$valueObject->getTelefono()."%' ";
          }

          if ($valueObject->getTelefono2() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND telefono2 LIKE '".$valueObject->getTelefono2()."%' ";
          }

          if ($valueObject->getUsername() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND username = '".$valueObject->getUsername()."' ";
          }

          if ($valueObject->getEstado() != 0) {
              if ($first) { $first = false; }
              $sql = $sql."AND estado = ".$valueObject->getEstado()." ";
          }

          if ($valueObject->getNombre() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND nombre LIKE '".$valueObject->getNombre()."%' ";
          }

          if ($valueObject->getCelular() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND celular LIKE '".$valueObject->getCelular()."%' ";
          }

          if ($valueObject->getEmail() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND email LIKE '".$valueObject->getEmail()."%' ";
          }

          if ($valueObject->getCertificacion() != 0) {
              if ($first) { $first = false; }
              $sql = $sql."AND certificacion = ".$valueObject->getCertificacion()." ";
          }

          if ($valueObject->getNivelestudio() != 0) {
              if ($first) { $first = false; }
              $sql = $sql."AND nivelestudio = ".$valueObject->getNivelestudio()." ";
          }

          if ($valueObject->getAprendices() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND aprendices LIKE '".$valueObject->getAprendices()."%' ";
          }

          if ($valueObject->getCursos() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND cursos LIKE '".$valueObject->getCursos()."%' ";
          }

          if ($valueObject->getFormatofoto() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND formatofoto LIKE '".$valueObject->getFormatofoto()."%' ";
          }

          if ($valueObject->getDepartamento() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND departamento LIKE '".$valueObject->getDepartamento()."%' ";
          }

            if ($valueObject->getCiudad() != "") {
              if ($first) { $first = false; }
              $sql = $sql."AND ciudad LIKE '".$valueObject->getCiudad()."%' ";
          }


          $sql = $sql."ORDER BY idArtesano ASC ";

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if ($first)
               return array();

          $searchResults = $this->listQuery($conn, $sql);

          return $searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    function databaseUpdate($conn, $sql) {

          $result = $conn->execute($sql);

          return $result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    function singleQuery($conn, $sql, $valueObject) {

          $result = $conn->execute($sql);

          if ($row = $conn->nextRow($result)) {

                   $valueObject->setIdArtesano($row[0]); 
                   $valueObject->setTipoDoc($row[1]); 
                   $valueObject->setNroDoc($row[2]); 
                   $valueObject->setPassword($row[3]); 
                   $valueObject->setDireccion($row[4]); 
                   $valueObject->setTelefono($row[5]); 
                   $valueObject->setTelefono2($row[6]); 
                   $valueObject->setUsername($row[7]); 
                   $valueObject->setEstado($row[8]); 
                   $valueObject->setNombre($row[9]); 
                   $valueObject->setCelular($row[10]); 
                   $valueObject->setEmail($row[11]); 
                   $valueObject->setCertificacion($row[12]); 
                   $valueObject->setNivelestudio($row[13]); 
                   $valueObject->setAprendices($row[14]); 
                   $valueObject->setCursos($row[15]); 
                   $valueObject->setFormatofoto($row[16]); 
                   $valueObject->setDepartamento($row[17]);
                   $valueObject->setCiudad($row[18]);
          } else {
               //print " Object Not Found!";
               return false;
          }
          return true;
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    function listQuery($conn, $sql) {

          $searchResults = array();
          $result = $conn->execute($sql);

          while ($row = $conn->nextRow($result)) {
               $temp = $this->createValueObject();

               $temp->setIdArtesano($row[0]); 
               $temp->setTipoDoc($row[1]); 
               $temp->setNroDoc($row[2]); 
               $temp->setPassword($row[3]); 
               $temp->setDireccion($row[4]); 
               $temp->setTelefono($row[5]); 
               $temp->setTelefono2($row[6]); 
               $temp->setUsername($row[7]); 
               $temp->setEstado($row[8]); 
               $temp->setNombre($row[9]); 
               $temp->setCelular($row[10]); 
               $temp->setEmail($row[11]); 
               $temp->setCertificacion($row[12]); 
               $temp->setNivelestudio($row[13]); 
               $temp->setAprendices($row[14]); 
               $temp->setCursos($row[15]); 
               $temp->setFormatofoto($row[16]); 
               $temp->setDepartamento($row[17]); 
               $temp->setCiudad($row[18]); 
               array_push($searchResults, $temp);
          }

          return $searchResults;
    }



    function encodificaraUTF($ValueObject)
    {
      $coded=$ValueObject;
      $coded->setNombre(utf8_encode($ValueObject->getNombre())); 
      $coded->setNroDoc(utf8_encode($ValueObject->getNroDoc())); 
      $coded->setPassword(utf8_encode($ValueObject->getPassword())); 
      $coded->setDireccion(utf8_encode($ValueObject->getDireccion())); 
      $coded->setTelefono(utf8_encode($ValueObject->getTelefono()));
      $coded->setTelefono2(utf8_encode($ValueObject->getTelefono2())); 
      $coded->setEmail(utf8_encode($ValueObject->getEmail())); 
      $coded->setUsername(utf8_encode($ValueObject->getUsername())); 
      $coded->setAprendices(utf8_encode($ValueObject->getAprendices()));
      $coded->setCursos(utf8_encode($ValueObject->getCursos())); 
      $coded->setCursos(utf8_encode($ValueObject->getDepartamento())); 
      $coded->setCursos(utf8_encode($ValueObject->getCiudad())); 
      return $coded;
    }
    function buscarArtesanoPorCedula($conn,$busqueda)
    {
      $sql="SELECT * FROM Artesano WHERE NroDoc LIKE '".$busqueda."%' ORDER BY nombre ASC;";
      
      return $this->listQuery($conn,$sql);
    }
    function buscarArtesanoPorNombre($conn,$busqueda)
    {      
      $sql="SELECT * FROM Artesano WHERE upper(nombre) LIKE '%".$busqueda."%' ORDER BY nombre ASC";
      return $this->listQuery($conn,$sql);
    }
    function buscarArtesanoPorCiudad($conn,$busqueda)
    {      
      $sql="SELECT * FROM Artesano WHERE ciudad =".$busqueda." ORDER BY nombre ASC";
      return $this->listQuery($conn,$sql);
    }
}

?>