<?php


 /**
  * Cursos Value Object.
  * This class is value object representing database table cursos
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Cursos {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $id;
    var $foto;
    var $descripcion;
    var $fecha_lim;
    var $horario;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Cursos () {

    }

    /* function Cursos ($idIn) {

          $this->id = $idIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getId() {
          return $this->id;
    }
    function setId($idIn) {
          $this->id = $idIn;
    }

    function getFoto() {
          return $this->foto;
    }
    function setFoto($fotoIn) {
          $this->foto = $fotoIn;
    }

    function getDescripcion() {
          return $this->descripcion;
    }
    function setDescripcion($descripcionIn) {
          $this->descripcion = $descripcionIn;
    }

    function getFecha_lim() {
          return $this->fecha_lim;
    }
    function setFecha_lim($fecha_limIn) {
          $this->fecha_lim = $fecha_limIn;
    }

    function getHorario() {
          return $this->horario;
    }
    function setHorario($horarioIn) {
          $this->horario = $horarioIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($idIn,
          $fotoIn,
          $descripcionIn,
          $fecha_limIn,
          $horarioIn) {
          $this->id = $idIn;
          $this->foto = $fotoIn;
          $this->descripcion = $descripcionIn;
          $this->fecha_lim = $fecha_limIn;
          $this->horario = $horarioIn;
    }


    /** 
     * hasEqualMapping-method will compare two Cursos instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getId() != $this->id) {
                    return(false);
          }
          if ($valueObject->getFoto() != $this->foto) {
                    return(false);
          }
          if ($valueObject->getDescripcion() != $this->descripcion) {
                    return(false);
          }
          if ($valueObject->getFecha_lim() != $this->fecha_lim) {
                    return(false);
          }
          if ($valueObject->getHorario() != $this->horario) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Cursos, mapping to table cursos\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."id = ".$this->id."\n"; 
        $out = $out."foto = ".$this->foto."\n"; 
        $out = $out."descripcion = ".$this->descripcion."\n"; 
        $out = $out."fecha_lim = ".$this->fecha_lim."\n"; 
        $out = $out."horario = ".$this->horario."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    function cloneObject() {
        $cloned = new Cursos();

        $cloned->setId($this->id); 
        $cloned->setFoto($this->foto); 
        $cloned->setDescripcion($this->descripcion); 
        $cloned->setFecha_lim($this->fecha_lim); 
        $cloned->setHorario($this->horario); 

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>